"""Compact operator workspace; auxiliary tools live in a modeless dialog."""
from PySide6.QtCore import Qt, Signal
from PySide6.QtGui import QActionGroup
from PySide6.QtWidgets import (QWidget, QLabel, QPushButton, QToolButton, QMenu,
    QVBoxLayout, QHBoxLayout, QComboBox, QCheckBox, QDialog, QTabWidget,
    QTextEdit, QLineEdit, QSizePolicy)
from grading_ui import GradingPanel


class ReviewMode(QComboBox):
    toggled = Signal(bool)

    def __init__(self):
        super().__init__()
        self.addItems(['즉시 반영', '검토 후 적용'])
        self.currentIndexChanged.connect(lambda index: self.toggled.emit(index == 1))
        self.setAccessibleName('보정 반영 방식')
        self.setToolTip('검토 모드에서는 적용을 눌러야 HDMI에 반영됩니다.\n즉시 반영으로 전환하면 미적용 변경을 취소합니다.')

    def setChecked(self, checked):
        self.setCurrentIndex(1 if checked else 0)

    def isChecked(self):
        return self.currentIndex() == 1


def button(title, callback, box=None):
    control = QPushButton(title)
    control.clicked.connect(callback)
    if box is not None:
        box.addWidget(control)
    return control


def build_main_ui(w, surface_class):
    body = QWidget()
    layout = QVBoxLayout(body)
    layout.setContentsMargins(16, 12, 16, 6)
    layout.setSpacing(12)
    bar = QHBoxLayout()
    bar.setSpacing(10)
    brand = QLabel('Goggles HDMI')
    brand.setObjectName('brand')
    brand.setToolTip('Goggles HDMI')
    bar.addWidget(brand)
    w.connection_badge = QLabel('연결 대기')
    w.connection_badge.setObjectName('muted')
    w.connection_badge.setMinimumWidth(66)
    bar.addWidget(w.connection_badge)
    w.usb_button = button('고글 연결', w.toggle_connection, bar)
    w.raw_button = QPushButton('원본 출력')
    w.raw_button.setCheckable(True)
    w.raw_button.setToolTip('검토 모드에서도 HDMI를 원본으로 전환합니다. 보정값은 유지됩니다.\n프로그램 활성 상태에서 Ctrl+B · 다시 누르면 적용된 보정으로 복귀')
    w.raw_button.toggled.connect(w.set_raw_output)
    bar.addWidget(w.raw_button)
    bar.addStretch(1)
    output_label = QLabel('출력 화면')
    output_label.setObjectName('muted')
    bar.addWidget(output_label)
    w.screens = QComboBox()
    w.screens.setMinimumWidth(190)
    w.screens.setMaximumWidth(310)
    w.screens.setSizeAdjustPolicy(QComboBox.AdjustToMinimumContentsLengthWithIcon)
    w.screens.setAccessibleName('HDMI 출력 화면 선택')
    bar.addWidget(w.screens, 1)
    w.output_button = button('출력 시작', w.toggle_output, bar)
    w.output_button.setToolTip('선택한 화면에 전체화면 출력 · Ctrl+D로 출력 종료')
    w.settings_button = button('설정', lambda: w.show_settings(0), bar)
    layout.addLayout(bar)
    w.update_notice = QWidget()
    notice = QHBoxLayout(w.update_notice)
    notice.setContentsMargins(8, 4, 8, 4)
    w.update_label = QLabel()
    w.update_label.setTextFormat(Qt.PlainText)
    w.update_label.setWordWrap(True)
    w.update_now = QPushButton('지금 업데이트')
    w.update_now.setToolTip('다운로드와 검증 후 영상 출력을 종료하고 설치·재시작합니다.')
    w.update_now.clicked.connect(lambda: w.program_panel.update_now())
    notice.addWidget(w.update_label, 1)
    notice.addWidget(w.update_now)
    layout.addWidget(w.update_notice)
    w.update_notice.hide()

    content = QHBoxLayout()
    content.setSpacing(14)
    viewer = QVBoxLayout()
    viewer.setSpacing(6)
    viewer_bar = QHBoxLayout()
    w.preview_context = QLabel('미리보기')
    w.preview_context.setObjectName('muted')
    viewer_bar.addWidget(w.preview_context, 1)
    w.compare = QCheckBox('원본 비교')
    w.compare.setToolTip('미리보기만 원본으로 표시합니다. HDMI 보정은 유지됩니다.')
    w.compare.toggled.connect(w.update_preview_policy)
    viewer_bar.addWidget(w.compare)
    w.view_options = QToolButton()
    w.view_options.setText('보기 ▾')
    w.view_options.setPopupMode(QToolButton.InstantPopup)
    viewer_bar.addWidget(w.view_options)
    viewer.addLayout(viewer_bar)
    w.preview = surface_class()
    w.preview.message = '고글을 연결하세요'
    viewer.addWidget(w.preview, 1)
    content.addLayout(viewer, 1)

    w.grading = GradingPanel()
    w.grading.changed.connect(w.set_look)
    w.staged = ReviewMode()
    w.staged.toggled.connect(w.set_staging)
    w.grading.mode_row.addWidget(w.staged)
    w.draft_status = QLabel()
    w.draft_status.setWordWrap(True)
    w.draft_status.setObjectName('muted')
    w.grading.footer.insertWidget(0, w.draft_status)
    w.draft_actions = QWidget()
    actions = QHBoxLayout(w.draft_actions)
    actions.setContentsMargins(0, 0, 0, 0)
    w.cancel_button = button('변경 취소', w.cancel_draft, actions)
    w.apply_button = button('출력에 적용', w.apply_draft, actions)
    w.apply_button.setObjectName('primary')
    w.grading.footer.insertWidget(1, w.draft_actions)
    content.addWidget(w.grading)
    layout.addLayout(content, 1)
    w.summary_status = button('영상 대기 · 출력 꺼짐', lambda: w.show_settings(2))
    w.summary_status.setObjectName('statusSummary')
    w.summary_status.setToolTip('클릭하여 수신·처리·출력 상세 진단 열기')
    w.summary_status.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
    layout.addWidget(w.summary_status)
    w.setCentralWidget(body)
    build_settings(w)
    build_view_menu(w)


def build_settings(w):
    w.settings_dialog = QDialog(w)
    w.settings_dialog.setWindowTitle('Goggles HDMI · 설정')
    w.settings_dialog.resize(660, 570)
    outer = QVBoxLayout(w.settings_dialog)
    outer.setContentsMargins(18, 18, 18, 14)
    outer.setSpacing(14)
    w.settings_tabs = QTabWidget()
    outer.addWidget(w.settings_tabs, 1)
    def page(title):
        widget = QWidget()
        box = QVBoxLayout(widget)
        box.setContentsMargins(16, 18, 16, 12)
        box.setSpacing(14)
        w.settings_tabs.addTab(widget, title)
        return box
    connection = page('연결·출력')
    w.warning = QLabel('Goggles 3 → USB → 노트북 → HDMI')
    connection.addWidget(w.warning)
    note = QLabel('고글에서 OTG 컴퓨터 연결과 라이브뷰 공유를 켠 뒤, 상단의 고글 연결을 누르세요.')
    note.setWordWrap(True)
    note.setObjectName('muted')
    connection.addWidget(note)
    row = QHBoxLayout()
    button('USB 최초 설정', w.setup_usb, row)
    button('연결 안내', w.show_guide, row)
    connection.addLayout(row)
    w.auto_fullscreen = QCheckBox('영상 수신 시 선택 화면으로 자동 출력')
    w.auto_fullscreen.setChecked(w.settings.value('autoFullscreen', False, type=bool) if w.settings else False)
    connection.addWidget(w.auto_fullscreen)
    button('출력 화면 새로고침', w.refresh_screens, connection)
    connection.addWidget(w.grading.restore_stabilizer)
    w.grading.restore_stabilizer.show()
    connection.addStretch()

    preview = page('미리보기·테스트')
    preview.addWidget(QLabel('미리보기 성능'))
    w.preview_mode = QComboBox()
    w.preview_mode.addItems(['전체 속도', '15 fps · 경량', '미리보기 끄기 · 출력 전용'])
    w.preview_mode.currentIndexChanged.connect(w.update_preview_policy)
    preview.addWidget(w.preview_mode)
    w.zebra_control = QCheckBox('노출 과다 표시')
    w.crop_control = QCheckBox('크롭 기준선 · 원본으로 보기')
    w.preview_crop = False
    for control in (w.zebra_control, w.crop_control):
        control.toggled.connect(w.update_preview_policy)
        preview.addWidget(control)
    note = QLabel('보기 옵션은 HDMI 출력에 포함되지 않습니다. 창을 최소화하면 미리보기가 일시 정지됩니다.')
    note.setWordWrap(True)
    note.setObjectName('muted')
    preview.addWidget(note)
    preview.addSpacing(8)
    preview.addWidget(QLabel('테스트 소스'))
    row = QHBoxLayout()
    w.source = QLineEdit()
    w.source.setPlaceholderText('영상 파일 또는 표준 스트림 주소')
    row.addWidget(w.source, 1)
    button('파일 선택', w.browse, row)
    preview.addLayout(row)
    row = QHBoxLayout()
    w.play_button = button('영상 재생', w.play, row)
    w.pattern_button = button('테스트 패턴', w.pattern, row)
    w.stop_button = button('수신·재생 정지', w.stop, row)
    preview.addLayout(row)
    preview.addStretch()

    diagnostics = page('진단')
    w.pipeline_status = QLabel('USB 미확인 · 영상 대기 · 출력 꺼짐')
    w.rate_status = QLabel('수신 — fps · 처리 — fps · 출력 화면 — Hz')
    w.status = QLabel('고글 USB 연결 대기')
    for label in (w.pipeline_status, w.rate_status, w.grading.performance, w.status):
        label.setWordWrap(True)
        diagnostics.addWidget(label)
        label.show()
    row = QHBoxLayout()
    w.diag_button = button('USB 연결 진단', w.diagnose, row)
    button('결과 저장', w.save_report, row)
    diagnostics.addLayout(row)
    row = QHBoxLayout()
    w.trace_button = button('타이밍 진단 · 30초 시작', w.toggle_trace, row)
    w.trace_save = button('타이밍 저장', w.save_trace, row)
    w.trace_save.setEnabled(False)
    diagnostics.addLayout(row)
    w.trace_status = QLabel('영상 없이 수신·처리·출력 그리기 시간만 기록')
    w.trace_status.setWordWrap(True)
    w.trace_status.setObjectName('muted')
    diagnostics.addWidget(w.trace_status)
    w.stutter_status = QLabel('자동 감지 대기 · 최근 5건의 시간 정보만 보관')
    w.stutter_status.setWordWrap(True)
    w.stutter_status.setObjectName('muted')
    tooltip = '100 ms 이상이며 평소 프레임 간격의 3.5배를 넘는 지연을 감지합니다.\n수신은 디코딩 이후, 표시는 프로그램의 화면 갱신 기준이며 물리 HDMI 지연 측정은 아닙니다.'
    if w.incident_store is not None:
        tooltip += '\n자동 저장: '+str(w.incident_store.path)
    w.stutter_status.setToolTip(tooltip)
    diagnostics.addWidget(w.stutter_status)
    w.stutter_save = button('끊김 기록 저장',w.save_stutter,diagnostics)
    w.stutter_save.setEnabled(False)
    w.logs = QTextEdit()
    w.logs.setReadOnly(True)
    w.logs.document().setMaximumBlockCount(300)
    diagnostics.addWidget(w.logs, 1)
    from program_ui import ProgramPanel
    w.program_panel = ProgramPanel(w)
    w.settings_tabs.addTab(w.program_panel, '프로그램')
    row = QHBoxLayout()
    row.addStretch()
    button('닫기', w.settings_dialog.close, row)
    outer.addLayout(row)


def build_view_menu(w):
    menu = QMenu(w)
    for control in (w.zebra_control, w.crop_control):
        action = menu.addAction(control.text())
        action.setCheckable(True)
        action.toggled.connect(control.setChecked)
        control.toggled.connect(action.setChecked)
    menu.addSeparator()
    group = QActionGroup(menu)
    group.setExclusive(True)
    for index in range(w.preview_mode.count()):
        action = menu.addAction(w.preview_mode.itemText(index))
        action.setCheckable(True)
        action.setChecked(index == 0)
        action.triggered.connect(lambda _, i=index: w.preview_mode.setCurrentIndex(i))
        group.addAction(action)
    w.preview_mode.currentIndexChanged.connect(lambda i: group.actions()[i].setChecked(True))
    w.view_options.setMenu(menu)
